@baseUrl = https://api.hyperliquid.xyz

### Get candle snapshot
POST {{baseUrl}}/info
Content-Type: application/json

{
    "type": "candleSnapshot",
    "req": {
        "coin": "BTC",
        "interval": "1m",
        "startTime": {{Date.now() - 86400000}},
        "endTime": {{Date.now()}}
    }
}

### Get meta
POST {{baseUrl}}/info
Content-Type: application/json

{
    "type": "meta"
}

### Get all mids
POST {{baseUrl}}/info
Content-Type: application/json

{
    "type": "allMids"
}
